ignore:
  - 'fflogsapi/user_auth.py' # explained in tests/user/test_user.py

coverage:
  status:
    project:
      source:
        paths:
        - 'fflogsapi/'
        target: 95%
    patch:
      default:
        target: 90%
