name: Tests

on:
  workflow_dispatch:
  push:
    paths:
    - '**.py'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: tests
    env:
      FFLOGSAPI_CID: ${{ secrets.FFLOGSAPI_CLIENT_ID }}
      FFLOGSAPI_SECRET: ${{ secrets.FFLOGSAPI_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e.[test]
    - name: Run caching tests with pytest
      run: |
        pytest tests/client/test_caching.py
    - name: Test with pytest
      run: |
        pytest

  coverage:
    runs-on: ubuntu-latest
    environment: tests
    env:
      FFLOGSAPI_CID: ${{ secrets.FFLOGSAPI_CLIENT_ID }}
      FFLOGSAPI_SECRET: ${{ secrets.FFLOGSAPI_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e.[test]
    - name: Test for code coverage
      run: |
        pytest --cov=fflogsapi
        mv .coverage .coverage-core
    - name: Test coverage of caching tests
      run: |
        pytest --cov=fflogsapi tests/client/test_caching.py
        mv .coverage .coverage-caching
    - name: Combine coverage reports
      run: |
        coverage combine .coverage-core .coverage-caching
        coverage xml
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3.1.1
